# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  windows: circleci/windows@2.2.0
  aws-cli: circleci/aws-cli@2.0

executors:
  docker-dotnet:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1

jobs:
  build-and-test-document-service:
    machine: true # Use a Linux VM instead of docker environment
    steps:
      - checkout
      - run:
          working_directory: ./backend/document-service/DocumentService
          name: build
          command: docker-compose build test
      - run:
          working_directory: ./backend/document-service/DocumentService
          name: Run tests
          command: docker-compose run test
  build-and-test-listener-service:
    machine: true # Use a Linux VM instead of docker environment
    steps:
      - checkout
      - run:
          working_directory: ./backend/DocumentServiceListener/DocumentServiceListener
          name: build
          command: docker-compose build listener-tests
      - run:
          working_directory: ./backend/DocumentServiceListener/DocumentServiceListener
          name: Run tests
          command: docker-compose run listener-tests
  deploy-document-service:
    executor: windows/default
    steps:
      - checkout
      - run:
          name: install-aws-extensions
          command: dotnet tool install -g Amazon.Lambda.Tools
      - run:
          working_directory: ./backend/document-service/DocumentService/DocumentService
          name: deploy
          command: dotnet-lambda deploy-function --function-name DocumentService

workflows:
  test-and-deploy:
    jobs:
      - build-and-test-document-service
      - build-and-test-listener-service
      - deploy-document-service:
          requires:
            - build-and-test-document-service
          filters:
            branches:
              only: main

