# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build-and-test:
    machine: true # Use a Linux VM instead of docker environment

    # docker:
      # - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    steps:
      - checkout
      - run:
          working_directory: ./backend/document-service/DocumentService
          name: build
          # command: docker-compose build test
          command: docker-compose build test
      - run:
          working_directory: ./backend/document-service/DocumentService
          name: Run tests
          # command: docker-compose run test
          command: docker-compose run test
  deploy:
    steps:
      - checkout
      - run:
          working_directory: ./backend/document-service/DocumentService/DocumentService
          name: deploy
          command: dotnet lambda deploy-function --function-name DocumentService
workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    jobs:
      - build-and-test
  deploy:
    jobs:
      - deploy:
        requires:
          - build-and-test
        # filters:
        #   branches:
        #     only: main
