version: "3.2"
services:
  document-service-listener-tests:
    image: document-service-listener-tests
    build:
      context: .
      dockerfile: DocumentServiceListener.Tests\Dockerfile
    ports:
      - 3000:3000
    environment:
      - DynamoDb_LocalMode=true
      - AWS_REGION=eu-west-1
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
      - Localstack_URL=http://document-service-listener-localstack:4566
    links:
      - document-service-listener-localstack

  document-service-listener-localstack:
    image: localstack/localstack:latest
    container_name: document-service-listener-localstack
    ports:
      - 127.0.0.1:4566:4566
    environment:
      - SERVICES=s3,dynamodb
      - DEBUG=1
      - LS_LOG=trace
    #  - DATA_DIR=/tmp/localstack/data
    volumes:
      - ./.localstack:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
